language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

before_install:
  - gem install bundler

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/mongoid_3.1.gemfile
  - gemfiles/nobrainer.gemfile

addons:
  code_climate:
    repo_token: b84a33c35c698270ad54261655bc25161a0853386825a2d54fb1c7a11c2b2785
